[package]
authors.workspace = true
description = "Vec extension methods"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-util"
repository.workspace = true
version.workspace = true


[dependencies]
