CREATE TABLE IF NOT EXISTS member (
    id SERIAL PRIMARY KEY,
    lyric_id UUID NOT NULL REFERENCES lyric ON DELETE CASCADE,
    playlist_id UUID NOT NULL REFERENCES playlist ON DELETE CASCADE,
    ordering INTEGER NOT NULL
);
