[package]
authors.workspace = true
description = "Axum webserver json api"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-server"
repository.workspace = true
version.workspace = true

[features]
default = ["memory", "postgres", "fs", "redis"]
postgres = ["dep:lipl-storage-postgres"]
memory = ["dep:lipl-storage-memory"]
fs = ["dep:lipl-storage-fs"]
redis = ["dep:lipl-storage-redis"]

[dependencies]
async-trait = "0.1"
axum = { version = "0.7", features = ["query"] }
futures-util = "0.3"
hyper = "1.0"
lipl-storage-postgres = { version = "0.4", path = "../lipl-storage-postgres", optional = true }
lipl-storage-memory = { version = "0.4", path = "../lipl-storage-memory", optional = true }
lipl-storage-fs = { version = "0.4", path = "../lipl-storage-fs", optional = true }
lipl-storage-redis = { version = "0.4", path = "../lipl-storage-redis", optional = true }
lipl-core = { version = "0.4", path = "../lipl-core" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["auth", "compression-br", "compression-gzip", "trace", "util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = "1"

[dev-dependencies]
serde_json = "1"
tower = { version = "0.4", features = ["full"] }
http-body-util = "0.1.0"
base64 = "0.21.6"
