[package]
authors.workspace = true
description = "Axum webserver json api"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-server"
repository.workspace = true
version.workspace = true

[features]
default = ["fs", "memory", "postgres", "pwa", "redis"]
postgres = ["dep:lipl-storage-postgres"]
memory = ["dep:lipl-storage-memory"]
fs = ["dep:lipl-storage-fs"]
redis = ["dep:lipl-storage-redis"]
pwa = ["tower-http/fs"]

[dependencies]
axum = { version = "0.8.4", features = ["http2"] }
futures-util = "0.3.31"
hyper = "1.6.0"
lipl-storage-postgres = { version = "0.5", path = "../lipl-storage-postgres", optional = true }
lipl-storage-memory = { version = "0.5", path = "../lipl-storage-memory", optional = true }
lipl-storage-fs = { version = "0.5", path = "../lipl-storage-fs", optional = true }
lipl-storage-redis = { version = "0.5", path = "../lipl-storage-redis", optional = true }
lipl-core = { version = "0.5", path = "../lipl-core" }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = [
  "rt-multi-thread",
  "macros",
  "signal",
] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = [
  "auth",
  "compression-br",
  "compression-gzip",
  "trace",
  "util",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
uuid = "1.17.0"

[dev-dependencies]
serde_json = "1.0.140"
tower = { version = "0.5.2", features = ["full"] }
http-body-util = "0.1.3"
base64 = "0.22.1"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.47"
