[package]
authors.workspace = true
description = "In Memory Storage for testing"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-memory"
repository.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1.59"
lipl-core = { version = "0.2.0", path = "../lipl-core" }
lipl-util = { version = "0.2.0", path = "../lipl-util" }
thiserror = "1.0.37"
lipl-sample-data = { version = "0.2.0", path = "../lipl-sample-data" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }