[package]
authors.workspace = true
description = "In Memory Storage for testing"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-storage-memory"
repository.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1.83"
lipl-core = { version = "0.5", path = "../lipl-core" }
thiserror = "2.0.0"
lipl-sample-data = { version = "0.5", path = "../lipl-sample-data" }

[dev-dependencies]
tokio = { version = "1.41.0", features = ["rt", "macros"] }

