[package]
authors.workspace = true
description = "Commandline utility to upload text files to http server"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-upload"
repository.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1"
anyhow = "1"
clap = { version = "4", features = ["derive", "cargo"] }
futures = "0.3"
lazy_static = "1"
lipl-core = { path = "../lipl-core" }
regex = "1"
rest-api-client = { version = "0.2.0", path = "../rest-api-client" }
thiserror = "1"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["fs"] }
